<a href="https://colab.research.google.com/github/DzhuJK/ML/blob/main/%D0%9B%D0%9A1_%D0%A2%D1%80%D0%B5%D0%BD%D1%83%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9_%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA_%D0%9B%D0%B5%D0%BA%D1%86%D1%96%D1%8F_2_NumPy_2026_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук до лекції 2  
## NumPy: масиви, векторизація та лінійна алгебра для машинного навчання

Ноутбук повторює та закріплює приклади, розглянуті в лекції.  
Усі основні приклади можна виконувати послідовно зверху вниз.

**Мета:** навчитися працювати з `ndarray`, індексацією, `dtype`, векторизацією, broadcasting, агрегуванням, зміною форми масивів, генерацією випадкових даних і засобами `numpy.linalg`.


## 1. Імпорт NumPy та перевірка версії

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


## 2. Створення `ndarray`

`ndarray` — основна структура NumPy. Усі елементи масиву мають узгоджений тип даних `dtype`.


In [ ]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)

M = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int64)

print("Вектор a:")
print(a)

print("\nМатриця M:")
print(M)

Вектор a:
[1. 2. 3. 4. 5.]

Матриця M:
[[1 2 3]
 [4 5 6]]


### Основні атрибути масиву

In [ ]:
print("shape:", M.shape)
print("ndim:", M.ndim)
print("size:", M.size)
print("dtype:", M.dtype)
print("itemsize:", M.itemsize)
print("nbytes:", M.nbytes)

shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8
nbytes: 48


### Самостійно
Створіть матрицю розміру `(3, 4)` та перевірте її `shape`, `ndim`, `size`, `dtype` і `nbytes`.


In [ ]:
ma = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Матриця:")
print(ma)

print("\nshape:", ma.shape)
print("ndim:", ma.ndim)
print("size:", ma.size)
print("dtype:", ma.dtype)
print("nbytes:", ma.nbytes)


Матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4)
ndim: 2
size: 12
dtype: int64
nbytes: 96


## 3. Спеціальні функції створення масивів

In [ ]:
a = np.array([1, 2, 3, 4])
zeros = np.zeros((2, 3), dtype=np.float32)
ones = np.ones((2, 3), dtype=np.int64)
full = np.full((2, 3), 7)
I = np.eye(4)

print("a =", a)
print("\nzeros =\n", zeros)
print("\nones =\n", ones)
print("\nfull =\n", full)
print("\nI =\n", I)

a = [1 2 3 4]

zeros =
 [[0. 0. 0.]
 [0. 0. 0.]]

ones =
 [[1 1 1]
 [1 1 1]]

full =
 [[7 7 7]
 [7 7 7]]

I =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### `arange` і `linspace`

In [ ]:
x1 = np.arange(0, 1, 0.2)
x2 = np.linspace(0, 1, num=6)

print("arange:", x1)
print("linspace:", x2)

arange: [0.  0.2 0.4 0.6 0.8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]


`np.arange(start, stop, step)` зручний, коли задається крок.  
`np.linspace(start, stop, num)` зручний, коли потрібно отримати точно задану кількість рівновіддалених значень.


## 4. Типи даних `dtype`

In [ ]:
x = np.array([1, 2, 3], dtype=np.int32)
y = x.astype(np.float32)

print("x.dtype:", x.dtype)
print("y.dtype:", y.dtype)

x.dtype: int32
y.dtype: float32


### Приклад змішаних типів

In [ ]:
a = np.array([1, 2, 3], dtype=np.float32)
b = np.float64(0.5)
c = a + b

print(c)
print("dtype результату:", c.dtype)

[1.5 2.5 3.5]
dtype результату: float64


### Самостійно
Створіть масив типу `float64` і перетворіть його на `float32`. Порівняйте `itemsize` і `nbytes`.


In [ ]:
# Ваш код
arr_float64 = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)

arr_float32 = arr_float64.astype(np.float32)

print("Масив float64:", arr_float64)
print("dtype:", arr_float64.dtype)
print("itemsize:", arr_float64.itemsize, "байт")
print("nbytes:", arr_float64.nbytes, "байт")

print("\nМасив float32:", arr_float32)
print("dtype:", arr_float32.dtype)
print("itemsize:", arr_float32.itemsize, "байт")
print("nbytes:", arr_float32.nbytes, "байт")

Масив float64: [1.1 2.2 3.3 4.4 5.5]
dtype: float64
itemsize: 8 байт
nbytes: 40 байт

Масив float32: [1.1 2.2 3.3 4.4 5.5]
dtype: float32
itemsize: 4 байт
nbytes: 20 байт


## 5. Індексація та зрізи

In [ ]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])
print(a[::2])

M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\nM[1, 1] =", M[1, 1])
print("M[1:, 1] =", M[1:, 1])
print("M[0, :2] =", M[0, :2])

10
50
[20 30 40]
[10 30 50]

M[1, 1] = 5
M[1:, 1] = [5 8]
M[0, :2] = [1 2]


### Булева індексація

In [ ]:
scores = np.array([56, 82, 91, 47, 73])
mask = scores >= 60

print("mask:", mask)
print("scores[mask]:", scores[mask])

passed = scores[scores >= 60]
print("passed:", passed)

mask: [False  True  True False  True]
scores[mask]: [82 91 73]
passed: [82 91 73]


### Розширена (fancy) індексація

In [ ]:
a = np.array([10, 20, 30, 40, 50])
idx = np.array([4, 0, 2])

print(a[idx])

[50 10 30]


### Самостійно
Із масиву `scores` виберіть лише значення від 70 до 90 включно.


In [ ]:
# Ваш код
result = scores[(scores >= 70) & (scores <= 90)]

print(result)

[82 73]


## 6. Представлення (`view`) та копія

In [ ]:
a = np.array([1, 2, 3, 4, 5])

view = a[1:4]
view[0] = 99

print("Після зміни view:")
print("a =", a)
print("view =", view)

a = np.array([1, 2, 3, 4, 5])

copy = a[1:4].copy()
copy[0] = 99

print("\nПісля зміни copy:")
print("a =", a)
print("copy =", copy)

Після зміни view:
a = [ 1 99  3  4  5]
view = [99  3  4]

Після зміни copy:
a = [1 2 3 4 5]
copy = [99  3  4]


Базовий зріз часто повертає **view**, тому зміна зрізу може змінити вихідний масив.  
Якщо потрібні незалежні дані, використовуйте `.copy()`.


## 7. Векторизація та універсальні функції

In [ ]:
values = [1, 2, 3, 4]

# Python
squared_loop = [x ** 2 for x in values]

# NumPy
a = np.array(values)
squared_numpy = a ** 2

print("Python:", squared_loop)
print("NumPy:", squared_numpy)

Python: [1, 4, 9, 16]
NumPy: [ 1  4  9 16]


### Поелементний і матричний добутки

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)
print("a @ b =", a @ b)

a + b = [5 7 9]
a * b = [ 4 10 18]
a @ b = 32


### Універсальні функції `ufunc`

In [ ]:
x = np.array([1.0, 4.0, 9.0])

print("sqrt:", np.sqrt(x))
print("log:", np.log(x))
print("maximum:", np.maximum(x, 5.0))

sqrt: [1. 2. 3.]
log: [0.         1.38629436 2.19722458]
maximum: [5. 5. 9.]


## 8. Broadcasting

In [ ]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([10, 20, 30])

print("X.shape:", X.shape)
print("bias.shape:", bias.shape)
print("\nX + bias =\n", X + bias)

X.shape: (2, 3)
bias.shape: (3,)

X + bias =
 [[11 22 33]
 [14 25 36]]


### Стандартизація за стовпцями через broadcasting

In [ ]:
X = np.array([
    [170., 65.],
    [180., 80.],
    [160., 55.]
])

mean = X.mean(axis=0)
std = X.std(axis=0)
X_scaled = (X - mean) / std

print("mean:", mean)
print("std:", std)
print("\nX_scaled =\n", X_scaled)

mean: [170.          66.66666667]
std: [ 8.16496581 10.27402334]

X_scaled =
 [[ 0.         -0.16222142]
 [ 1.22474487  1.29777137]
 [-1.22474487 -1.13554995]]


### Самостійно
До кожного стовпця матриці додайте різне число за допомогою broadcasting.


In [ ]:
# Ваш код
i = np.array([
    [10, 30, 54],
    [40, 23, 44],
    [65, 73, 11]
])

c= np.array([19, 39, 88])
print("\ni + c =\n", i + c)
print("i.shape:", i.shape)
print("c.shape:", c.shape)



i + c =
 [[ 29  69 142]
 [ 59  62 132]
 [ 84 112  99]]
i.shape: (3, 3)
c.shape: (3,)


## 9. Агрегування та параметр `axis`

In [ ]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("sum:", M.sum())
print("sum(axis=0):", M.sum(axis=0))
print("sum(axis=1):", M.sum(axis=1))
print("mean(axis=0):", M.mean(axis=0))

sum: 21
sum(axis=0): [5 7 9]
sum(axis=1): [ 6 15]
mean(axis=0): [2.5 3.5 4.5]


### Робота з `NaN`

In [ ]:
x = np.array([10.0, np.nan, 30.0, 40.0])

print("np.mean(x):", np.mean(x))
print("np.nanmean(x):", np.nanmean(x))

np.mean(x): nan
np.nanmean(x): 26.666666666666668


Корисні агрегувальні функції: `sum`, `mean`, `median`, `std`, `var`, `min`, `max`, `argmin`, `argmax`, `quantile`, `percentile`.


## 10. Зміна форми масивів

In [ ]:
a = np.arange(12)
M = a.reshape(3, 4)

print("M =\n", M)
print("\nM.T =\n", M.T)
print("\nravel:", M.ravel())
print("flatten:", M.flatten())

M =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

M.T =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Додавання нової осі

In [ ]:
x = np.array([1, 2, 3])

row = x[np.newaxis, :]
col = x[:, np.newaxis]

print("x.shape:", x.shape)
print("row.shape:", row.shape)
print("col.shape:", col.shape)

print("\nrow =\n", row)
print("\ncol =\n", col)

x.shape: (3,)
row.shape: (1, 3)
col.shape: (3, 1)

row =
 [[1 2 3]]

col =
 [[1]
 [2]
 [3]]


## 11. Об’єднання масивів

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("concatenate axis=0:\n", np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n", np.concatenate([a, b], axis=1))
print("\nvstack:\n", np.vstack([a, b]))
print("\nhstack:\n", np.hstack([a, b]))

concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]


### `stack` створює нову вісь

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

S = np.stack([x, y], axis=0)

print(S)
print("shape:", S.shape)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)


## 12. Випадкові числа: сучасний `Generator API`

In [ ]:
rng = np.random.default_rng(seed=42)

uniform = rng.random(5)
normal = rng.normal(loc=0.0, scale=1.0, size=5)
integers = rng.integers(0, 10, size=5)

print("uniform:", uniform)
print("normal:", normal)
print("integers:", integers)

uniform: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
normal: [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
integers: [5 3 1 9 7]


### Перемішування та випадкова вибірка

In [ ]:
rng = np.random.default_rng(123)

idx = np.arange(10)
rng.shuffle(idx)

sample = rng.choice(np.arange(100), size=5, replace=False)

print("shuffled idx:", idx)
print("sample:", sample)

shuffled idx: [7 4 0 2 1 5 6 8 3 9]
sample: [77 43 90 27 44]


### Самостійно
Згенеруйте:
- матрицю `(4, 3)` із нормального розподілу;
- 10 випадкових цілих чисел від 1 до 100;
- випадкову вибірку з 5 різних індексів із діапазону `0..19`.


In [ ]:
# Ваш код
a = np.random.randn(4, 3)
b = np.random.randint(1, 101, size=10)
c = np.random.choice(20, size=5, replace=False)

print("Нормальний розподіл:", a)
print("10 випадкових чисел:", b)
print(c)

Нормальний розподіл: [[-1.24185428 -0.10487426 -0.62481158]
 [ 0.50192452  0.40193919  0.02751467]
 [ 0.84815423  0.7273073  -1.52359826]
 [-0.76842869 -0.73693733  1.02129545]]
10 випадкових чисел: [49 63 63 25 71 38 73 12 79 80]
[ 1 11  2  5  6]


## 13. Лінійна алгебра

### Матричний добуток

In [ ]:
A = np.array([
    [1, 2, 3],
    [0, 1, 2]
])

B = np.array([
    [ 1, 2],
    [ 0, 4],
    [-1, 0]
])

C = A @ B
print(C)

[[-2 10]
 [-2  4]]


### Діагональ, транспонування та визначник

In [ ]:
A = np.array([
    [ 1.,  0., 3.],
    [-1., -1., 2.],
    [ 4.,  7., 2.]
])

print("diag:", np.diag(A))
print("\nA.T =\n", A.T)

det = np.linalg.det(A)
print("\ndet(A) =", det)
print("det близький до -25:", np.isclose(det, -25.0))

diag: [ 1. -1.  2.]

A.T =
 [[ 1. -1.  4.]
 [ 0. -1.  7.]
 [ 3.  2.  2.]]

det(A) = -24.999999999999996
det близький до -25: True


### Розв’язання системи `Ax = b`

In [ ]:
A = np.array([
    [1.,  2.,  5.],
    [1., -1.,  3.],
    [3., -6., -1.]
])

b = np.array([-9., 2., 25.])

x = np.linalg.solve(A, b)

print("x =", x)
print("Перевірка A @ x ≈ b:", np.allclose(A @ x, b))

x = [ 2. -3. -1.]
Перевірка A @ x ≈ b: True


Для розв’язання системи не потрібно явно обчислювати `A⁻¹`.  
У числових обчисленнях перевага надається `np.linalg.solve(A, b)`.


### Метод найменших квадратів

In [ ]:
X = np.array([
    [1., 1.],
    [1., 2.],
    [1., 3.],
    [1., 4.]
])

y = np.array([2.1, 3.9, 6.2, 8.1])

beta, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)

print("beta:", beta)
print("residuals:", residuals)
print("rank:", rank)
print("singular values:", s)

beta: [6.9423189e-16 2.0300000e+00]
residuals: [0.043]
rank: 2
singular values: [5.77937881 0.77380911]


### Власні значення та власні вектори

In [ ]:
A = np.array([
    [2., 1.],
    [1., 2.]
])

values, vectors = np.linalg.eigh(A)

print("Власні значення:", values)
print("Власні вектори:\n", vectors)

Власні значення: [1. 3.]
Власні вектори:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


### SVD

In [ ]:
A = np.array([
    [3., 1.],
    [1., 3.],
    [1., 1.]
])

U, s, Vt = np.linalg.svd(A, full_matrices=False)

print("U =\n", U)
print("\ns =", s)
print("\nVt =\n", Vt)

U =
 [[-6.66666667e-01  7.07106781e-01]
 [-6.66666667e-01 -7.07106781e-01]
 [-3.33333333e-01  5.92577380e-18]]

s = [4.24264069 2.        ]

Vt =
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


## 14. NumPy у задачах машинного навчання

### 14.1. Стандартизація ознак

In [ ]:
X = np.array([
    [170., 65., 25.],
    [180., 80., 31.],
    [160., 55., 22.],
    [175., 72., 28.]
])

mu = X.mean(axis=0)
sigma = X.std(axis=0)
X_std = (X - mu) / sigma

print("Середні після стандартизації:")
print(X_std.mean(axis=0))

print("\nСтандартні відхилення:")
print(X_std.std(axis=0))

Середні після стандартизації:
[0.00000000e+00 0.00000000e+00 1.38777878e-17]

Стандартні відхилення:
[1. 1. 1.]


### 14.2. Лінійна модель без циклу

In [ ]:
X = np.array([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 4.0]
])

w = np.array([0.5, -0.25])
b = 1.0

y_pred = X @ w + b

print(y_pred)

[1.   1.75 1.5 ]


### 14.3. Середньоквадратична помилка

In [ ]:
y_true = np.array([1.2, 1.8, 2.5])
y_pred = np.array([1.0, 2.0, 2.3])

mse = np.mean((y_true - y_pred) ** 2)

print("MSE =", mse)

MSE = 0.04000000000000001


### 14.4. Евклідова відстань до набору об’єктів

In [ ]:
X = np.array([
    [1., 2.],
    [4., 6.],
    [2., 3.]
])

q = np.array([1., 1.])

distances = np.linalg.norm(X - q, axis=1)

print(distances)

[1.         5.83095189 2.23606798]


## 15. Сортування, пошук і вибір

In [ ]:
x = np.array([7, 2, 9, 2, 5])

print("sort:", np.sort(x))
print("argsort:", np.argsort(x))
print("unique:", np.unique(x))
print("where x >= 5:", np.where(x >= 5))
print("clip 3..7:", np.clip(x, 3, 7))

sort: [2 2 5 7 9]
argsort: [1 3 4 0 2]
unique: [2 5 7 9]
where x >= 5: (array([0, 2, 4]),)
clip 3..7: [7 3 7 3 5]


## 16. Збереження та завантаження масивів

In [ ]:
X = np.arange(12).reshape(3, 4)

np.save("X.npy", X)
X_loaded = np.load("X.npy")

print("X_loaded.shape:", X_loaded.shape)
print(X_loaded)

np.savez_compressed(
    "dataset.npz",
    X=X,
    y=np.array([0, 1, 1])
)

data = np.load("dataset.npz")
print("\ndata['X'] =\n", data["X"])
print("data['y'] =", data["y"])

X_loaded.shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

data['X'] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
data['y'] = [0 1 1]


## 17. Числова стабільність і перевірка даних

In [ ]:
x = np.array([1.0, np.nan, np.inf, -5.0])

print("isfinite:", np.isfinite(x))
print("Скінченні значення:", x[np.isfinite(x)])

isfinite: [ True False False  True]
Скінченні значення: [ 1. -5.]


### Порівняння чисел із плаваючою комою

In [ ]:
a = 0.1 + 0.2
b = 0.3

print("a == b:", a == b)
print("np.isclose(a, b):", np.isclose(a, b))

a == b: False
np.isclose(a, b): True


## 18. Узагальнюючий приклад: підготовка даних і лінійний прогноз

In [ ]:
# 1. Вхідні дані: два фактори та цільова змінна
X = np.array([
    [10., 2.],
    [12., 3.],
    [15., 4.],
    [18., 5.],
    [20., 6.]
])

y = np.array([21., 25., 31., 36., 40.])

# 2. Фільтрація
mask = np.isfinite(X).all(axis=1) & np.isfinite(y)
X = X[mask]
y = y[mask]

# 3. Стандартизація ознак
mu = X.mean(axis=0)
sigma = X.std(axis=0)
X_std = (X - mu) / sigma

# 4. Додаємо стовпець одиниць для вільного члена
X_design = np.column_stack([
    np.ones(X_std.shape[0]),
    X_std
])

# 5. Оцінювання параметрів методом найменших квадратів
beta, *_ = np.linalg.lstsq(X_design, y, rcond=None)

# 6. Прогноз і MSE
y_pred = X_design @ beta
mse = np.mean((y - y_pred) ** 2)

print("beta =", beta)
print("y_pred =", y_pred)
print("MSE =", mse)

beta = [30.6         5.53172667  1.41421356]
y_pred = [21.1 25.1 30.6 36.1 40.1]
MSE = 0.03999999999999986


## 19. Підсумкові тренувальні завдання

1. Створіть матрицю `X` форми `(5, 4)` із випадкових чисел.
2. Обчисліть середнє та стандартне відхилення кожної ознаки.
3. Стандартизуйте матрицю через broadcasting.
4. Виберіть рядки, у яких значення першої ознаки додатне.
5. Додайте до матриці новий стовпець одиниць.
6. Створіть вектор ваг і обчисліть прогноз `X @ w`.
7. Для заданого `y_true` обчисліть MSE.
8. Перевірте, чи немає в масивах `NaN` або `inf`.


In [ ]:
# Виконайте підсумкове завдання тут
rng = np.random.default_rng(seed=42)

# 1. Створення випадкової матриці X (5, 4) та цільового вектора y_true
X = rng.standard_normal((5, 4))
y_true = np.array([1.5, 2.0, -0.5, 3.2, 1.1])

print("Матриця X:\n", X)
print("\nВектор y_true:", y_true)

# 2. Перевірка на відсутність NaN або inf у масивах
d= not np.all(np.isfinite(X)) or not np.all(np.isfinite(y_true))
print("\nПеревірка на NaN & inf:", d)

# Фільтрація валідних рядків
mask = np.isfinite(X).all(axis=1) & np.isfinite(y_true)
X = X[mask]
y_true = y_true[mask]

# 3. Вибір рядків, у яких значення першої ознаки додатне
p_mask = X[:, 0] > 0
X_fil = X[p_mask]
y_fil = y_true[p_mask]

print("\nБулева маска (перша ознака > 0):", p_mask)
print("\nВідфільтрована матриця X:\n", X_fil)
print("\nВідфільтровані значення y_true:", y_fil)

# 4. Обчислення середнього та стандартного відхилення кожної ознаки
mu = X_fil.mean(axis=0)
sigma = X_fil.std(axis=0)

print("\nСереднє значення (mu):", mu)
print("Стандартне відхилення (sigma):", sigma)

# 5. Стандартизація матриці через broadcasting
X_std = (X_fil - mu) / sigma

print("\nСтандартизована матриця X_std:\n", X_std)

# 6. Додавання стовпця одиниць
random_column = rng.standard_normal(X_std.shape[0])
X_design = np.column_stack([random_column, X_std])

print("\nМатриця з доданим стовпцем одиниць:\n", X_design)

# 7. Створення вектора ваг w та обчислення прогнозу
w = np.array([0.5, -1.2, 0.8, 0.3, -0.5])
y_pred = X_design @ w

print("\nВектор ваг w:", w)
print("Прогнозовані значення (y_pred):", y_pred)

# 8. Обчислення MSE
mse = np.mean((y_fil - y_pred) ** 2)

print("\nMSE:", mse)

Матриця X:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826   0.8784503  -0.04992591]]

Вектор y_true: [ 1.5  2.  -0.5  3.2  1.1]

Перевірка на NaN & inf: False

Булева маска (перша ознака > 0): [ True False False  True  True]

Відфільтрована матриця X:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [ 0.0660307   1.12724121  0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826   0.8784503  -0.04992591]]

Відфільтровані значення y_true: [1.5 3.2 1.1]

Середнє значення (mu): [ 0.24649952 -0.29054183  0.69880361  0.01044878]
Стандартне відхилення (sigma): [0.13026083 1.00307059 0.17169493 0.73602776]

Стандартизована матриця X_std:
 [[ 0.44693066 -0.74714808  0.30081018  1.26369682]
 [-1.38544198  1.41344293 -1.34712349 -1.18166908]
 [ 0.93851132 -0.66629485  1.04631331 -0.08202774]]

Матриця з доданим стовпц

## Контрольні запитання

1. Чим `ndarray` відрізняється від списку Python?
2. Що означають `shape`, `ndim`, `size`, `dtype`, `itemsize`?
3. У чому різниця між `np.arange` і `np.linspace`?
4. Чим `view` відрізняється від `copy`?
5. Що таке векторизація?
6. Які правила broadcasting?
7. Як трактувати `axis=0` і `axis=1`?
8. Чим відрізняються `*` та `@`?
9. Чому для `Ax=b` краще використовувати `np.linalg.solve`?
10. Чому для нового коду рекомендовано `np.random.default_rng()`?
